name: Terraform security scan

on:
  push:
    branches:
    - main
    - master
  pull_request:
    branches:
    - main
    - master

jobs:
  tfsec_scan:
    name: Terraform security scan
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      pull-requests: write
      security-events: write

    steps:

    - name: Clone repo
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Run tfsec PR commenter
      uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run tfsec
      uses: aquasecurity/tfsec-sarif-action@master
      with:
        sarif_file: tfsec.sarif

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: tfsec.sarif

            
