name: Run security KICS scaner

on: 
  # workflow_dispatch
  pull_request:
    branches:
    - main

jobs:
  kics:
    name: Run security KICS scaner
    runs-on: "ubuntu-latest"

    steps:
    - name: Checkout code repo
      uses: actions/checkout@v3

    - name: Run security KICS scaner
      uses: checkmarx/kics-github-action@v1.7.0
      with:
        path: .
        enable_comments: true
        # enable_annotations: true
        ignore_on_exit: results
