name: Run security KICS scaner

on: #workflow_dispatch
  # push:
  pull_request:
    branches:
    - main

jobs:
  kics:
    name: Run security KICS scaner
    runs-on: "ubuntu-latest"
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout code repo
      uses: actions/checkout@v3

    - name: Run security KICS scaner
      uses: checkmarx/kics-github-action@v1.7.0
      with:
        path: .
        # output_path: myResults/
        enable_comments: true
        enable_annotations: true
        token: ${{ secrets.GITHUB_TOKEN }}
        verbose: true
        ignore_on_exit: results

    # - name: Upload KICS scan results to GitHub Security tab
    #   uses: github/codeql-action/upload-sarif@v3
    #   with:
    #     sarif_file: 'results.sarif'
