name: Perform Terrascan Action

on: 
  # workflow_dispatch
  push:
    # branches:
    # - main
    # - master
  pull_request:
    branches:
    - main
    - master

jobs:
  terrascan_job:
    name: Perform Terrascan Action
    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v3

    - name: Run Terrascan
      id: terrascan
      uses: tenable/terrascan-action@main
      with:
        iac_type: 'terraform'
        iac_version: 'v14'
        only_warn: true
        sarif_upload: true
        #non_recursive:
        #policy_path:
        #skip_rules:
        #config_path:
          
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: terrascan.sarif
