name: Run Trivy vulnerability scanner

on: workflow_dispatch
  # push:
  # pull_request:
  #   # The branches below must be a subset of the branches above
  #   branches:
  #   - main

jobs:
  scan:
    name: Run Trivy vulnerability scanner
    runs-on: "ubuntu-20.04"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Trivy vulnerability scanner in IaC mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'config'
        hide-progress: false
        format: 'sarif'
        output: 'trivy-results.sarif'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'
